name: E2E Test 
on:
  push:
    branches: [ master ] pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        wp-version: ['5.7.2']
        containers: [1, 2, 3, 4, 5]
        stackable-versions: ['v2']
        test-by: ['(features|theme|integrations)','blocks']

    steps:
    - uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Setup the Stackable Free and Premium Repository
      run: |
        git clone https://github.com/gambitph/Stackable.git
        cd Stackable
        git clone https://${{ secrets.ACCESS_KEY }}@github.com/bfintal/Stackable-Premium pro__premium_only
        cd ..

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install @wordpress/env
      run: npm install -g @wordpress/env

    - name: Build Stackable Premium
      run: |
        cd Stackable
        npm ci
        cd pro__premium_only
        npm ci
        npm run build --if-present

    - name: Install WordPress Version
      run: |
        curl -LO https//wordpress.org/wordpress-${{ matrix.wp-version }}.zip
        mkdir wordpress
        mv wordpress-${{ matrix.wp-version }}.zip wordpress/build.zip

    - name: Run WordPress Local Environment 
      run: |
        wp-env start
  


